# PBS flags
queue: express
project: g40
walltime: 1:00:00
ncpus: 24
# npernode: 12
mem: 60GB 
jobname: om3_core_test

# collate: true
collate: false

collate_walltime: 4:00:00
collate_mem: 30GB
collate_flags: -n4 -z -m

# System environment
stacksize: unlimited

shortpath: /short/v45

runlog: true

mpiP: true

# Model config
model: mom
# exe: mom51_sis_ompi184_debug_5kmethods
exe: mom51_sis_xgrid
input:
    - om3_core3

