# PBS flags
queue: express
project: x77
walltime: 0:10:00
ncpus: 96
mem: 180GB 
jobname: om3_core_test
join: oe

# archive: false

# collate: true
collate: false

collate_walltime: 4:00:00
collate_mem: 30GB
collate_flags: -v -n4 -z -m -r
collate_ncpus: 8
collate_queue: express

# System environment
stacksize: unlimited

shortpath: /short/v45

runlog: true

qsub_flags: -W umask=027

# mpiP: true

restart: true

# Model config
model: mom
# exe: mom51_sis_ompi184_debug_5kmethods
exe: fms_MOM_SIS.intel14.fpe0.O3
# exe: fms_MOM_SIS_matt.x
input:
    - mom10/mask_96
    - om3_core3

