# PBS flags
queue: express
project: v45
walltime: 1:00:00
ncpus: 24
# npernode: 12
mem: 60GB 
jobname: om3_core_test
join: oe

collate: true
# collate: false

collate_walltime: 4:00:00
collate_mem: 30GB
collate_flags: -v -n4 -z -m -r
collate_ncpus: 8
collate_queue: express
collate: false

# System environment
stacksize: unlimited

shortpath: /short/v45

runlog: true

# mpiP: true

# Model config
model: mom
# exe: mom51_sis_ompi184_debug_5kmethods
# exe: mom51_sis_xgrid
exe: fms_MOM_SIS_matt.x
input:
    - om3_core3

